### ISSUE TITLE
SyntaxError: more than 255 arguments

### ISSUE THREAD

**Issue by tyralla** [tyralla/hydpy#11]
Until recently, Python did not allow for more than 255 function arguments.  This arbitrary restriction has been removed in Python 3.7 (see https://bugs.python.org/issue12844).  But at the moment it still persists for all other Python versions.

Usually, one has not to bother with this restriction, as most HydPy methods do accept only a very small number of arguments. But it can be a problem for extremely large (or spatially detailed) model configurations.  Then it is not possible to define e.g. the individual field capacity values of thousand grid cells of one subbasin as individual function arguments:

```python
field_capacity(1., 2., 3., ... ,998., 999., 1000.)
```

When writing the control parameters on your own, the solution is quite simple.  For a 1-dimensional parameter, just bundle up all individual values in something like a plain list:

```python
field_capacity([1., 2., 3., ... ,998., 999., 1000.])
```

In the given example, 1000 function arguments are reduced to a single one.

But two things should be improved in the core of the HydPy framework:
- [ ] return a more informative error message, when a user uses too many function arguments
- [x] improve all affected __repr__ methods, to make sure the do not return string representations using too many function arguments

**Comment by wuestenfeld** [comment]
Reffering to this issue another problem occurs. When using hp.saveconditions(), the written file can not be reloaded with hp.loadconditions(). 

SyntaxError: While trying to gather initial conditions of element subbasin, the following error occured: more than 255 arguments (<string>, line 5)

If there are more than 255 arguments, there should be [ ] around the values. After that, they can be reloaded easily.

**Comment by tyralla** [comment]
Commit 0cbe3768b6cc6daf582c78c4444429632de3180f should solve the mentioned problem. Currently, it is available in the develop branch only. I will merge it into the master branch, as soon as you confirm its functionality.
