### ISSUE TITLE
RuntimeError: Trying to build node connection

### ISSUE THREAD

**Issue by wuestenfeld** [tyralla/hydpy#12]
An error occurs due to the fact that GlobWat routing works without branches. One node can have more than one inlets, e.g. one catchment has inlets from more than one head catchment.

RuntimeError: While trying to build the node connection of the `inlet` sequences of the model handled by element `bodrog`, the following error occured: Sequence `q` cannot be connected, as it is 0-dimensional but multiple nodes are available which are handling variable `Q`.

**Comment by tyralla** [comment]
This seems to be a problem of the current GlobWat implementation, or possible of your network file.

Node instances can always have multiple entries. But if the same is true for Element instances depends on the type of model they are handling. 

Your inlet sequence "Q" is 0-dimensional, meaning it handles only one value at a time.  This is fine, if there is always exactly one inlet node for each element.  But if you want to allow for different numbers of inlet nodes, you to make your inlet sequence 1-dimensional. Essentially, you have to set the class attribute NDIM to 1.

I suggest, you adapt the modules "lstream_inlets", "lstream_outlets", and the method "update_inlets_v1" to your GlobWat implementation. "lstream_inlets" and "lstream_outlets" replace "lstream_links", which allows for defining an inlet sequence "Q" and an outlet sequence "Q" with different dimensionality. "update_inlets_v1" includes a for loop, to sum up all input values.

**Comment by wuestenfeld** [comment]
This was very helpful, so I could fix the error.
