### ISSUE TITLE
RuntimeError: trying to build the node connection

### ISSUE THREAD

**Issue by wuestenfeld** [tyralla/hydpy#13]
While trying to initialize GlobWat model an error occurs.  

RuntimeError: While trying to build the node connection of the `inlet` sequences of the model handled by element `archar`, the following error occured: The shape of `PPDouble` of instances must not be changed.

**Comment by tyralla** [comment]
I do not have access to the branch you are currently working on.  But the message is quite clear: you are allowed to set the shape of PPDouble instances only on time. 

I suspect, you called a NmbGrids instance beforehand. Maybe your latest version of this class is still (without docstrings and comments):

```python
class NmbGrids(parametertools.SingleParameter):
    NDIM, TYPE, TIME, SPAN = 0, int, None, (1, None)

    def __call__(self, *args, **kwargs):
        parametertools.SingleParameter.__call__(self, *args, **kwargs)
        for (_name, subpars) in self.subpars.pars.model.parameters:
            for (name, par) in subpars:
                if (par.NDIM==1):
                    par.shape = self.value
        for (_name, subseqs) in self.subpars.pars.model.sequences:
            for (name, seq) in subseqs:
                if (seq.NDIM==1):
                    seq.shape = self.value
```
Hence, the shape of all 1-dimensional Parameter and Sequence instances is set to the value of the related NmbGrids instance.  This makes sense for spatially distributed parameters and sequences, but not for the inflow into a catchment.  So replace

```python
            for (name, seq) in subseqs:
                if (seq.NDIM==1):
                    seq.shape = self.value
```

with 

```python
            for (name, seq) in subseqs:
                if (seq.NDIM==1) and (name != 'q'):
                    seq.shape = self.value
```

or something like

```python
            for (name, seq) in subseqs:
                if (seq.NDIM==1) and not isinstance(seq, parametertools.LinkSequence):
                    seq.shape = self.value
```

Please let me know, if this advice did help you to solve your problem (please do the same for the related issue #12).

**Comment by wuestenfeld** [comment]
Thanks for your help. Replacing 
        for (name, seq) in subseqs:
                if (seq.NDIM==1):
                    seq.shape = self.value
with
            for (name, seq) in subseqs:
                if (seq.NDIM==1) and (name != 'q'):
                    seq.shape = self.value
works!
