### ISSUE TITLE
UserWarning by missing external data

### ISSUE THREAD

**Issue by GoHorn** [tyralla/hydpy#14]
Using prepare_nodeseries, HydPy tries to perpare every node, also the nodes without external obs data. This leads to the fact that HydPy throws a UserWarning for every node with missing obs series. For large catchments with many subbasins and only a few obs sequences this is confusing.

UserWarning: The option `ramflag` of the simulation sequence had to be set to `False` due to the following problem: While trying to load the external data of sequence `obs` from file, the following error occured: [Errno 2] No such file or directory:

**Comment by tyralla** [comment]
I addressed this issue in commits a9a0007b6100a2e33eee673dc96269d0d3a386c9, f28ce531310b3f10bd2549a68bae19e08e71f37d and d6f7678e667120229e5bc17f0f32c1843c4b364d.

Now you can write 

````python
pub.options.warnmissingobsfile = False
````
to generally disable the warning message.

Please let me know if this works in your project or if there are any negative side effects.

**Comment by GoHorn** [comment]
Your commit solved this problem.
Thank you for your fast response!
