### ISSUE TITLE
Warning

### ISSUE THREAD

**Issue by wuestenfeld** [tyralla/hydpy#19]
While running globwat model a warning occurs, but it is not clear which element(s) is/are trimmed. It would be helpful if here were a hint which elemet ist trimmed, so that this could be fixed.

\hydpy\core\parametertools.py:408: UserWarning: For parameter scmax of element ? at least one value needed to be trimmed.  Two possible reasons could be that the a parameter bound violated or that the values of two (or more) different parameters are inconsistent.
  % (self.name, objecttools.devicename(self)))

**Comment by tyralla** [comment]
You're right.  During model initialization, the "trim warning" has been raised before the connection between the model and its element was available.  Hence, the warning message could not include the name of the associated element.

I fixed this in commit 7f12f28e958031ab3cdab2baed83bd684feeb60f by changing the order in which the connection is build and the parameters are initialized.

Currently, the commit is available in the develop branch only. Please let me know if everything works well.  I will merge it into the master branch afterwards.

**Comment by wuestenfeld** [comment]
the trim warning works pretty well now.
