### ISSUE TITLE
initgrid and loadconditions

### ISSUE THREAD

**Issue by GoHorn** [tyralla/hydpy#30]
There is no warning when the date of the initial conditons and the firstdate of the initgrid are different. The simulation just starts without initvals.

**Comment by tyralla** [comment]
Hi Gordon,

I tried to reproduce your problem in my current project.  But in my case, an exception has been raised.

After correcting the exception message in commit eaa0385e6d332101f8595e38814d38d20234a351, the exact output is:

```python
OSError: The project path `...` contains at least one directory, but none is in accordance with the first simulation date (init_2006_01_02_00_00_00).  Please specify the condition directory to be worked with manually.
```

My test script is quite simple:

```python
from hydpy import pub, HydPy, Timegrid, Timegrids
pub.timegrids = Timegrids(Timegrid('2006.01.02', '2015.11.01', '1h'))
hp = HydPy('...')
hp.preparenetwork()
hp.initmodels()
hp.loadconditions()
```

Do you see any differences between our scripts?
